/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    copy: typeof import('./src/components/SidebarComponent copy.vue')['default']
    GenerationComponent: typeof import('./src/components/GenerationComponent.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MainContentComponent: typeof import('./src/components/MainContentComponent.vue')['default']
    RegressionComponent: typeof import('./src/components/RegressionComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarComponent: typeof import('./src/components/SidebarComponent.vue')['default']
  }
}
